<?php

/**
 * @file
 * Module definition.
 */

/**
 * Implements hook_theme().
 */
function auth0_theme(): array {
  return [
    'auth0_login' => [
      'template' => 'auth0-login',
      'variables' => [
        'loginCSS' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_library_info_build().
 */
function auth0_library_info_build(): array {
  $config = \Drupal::service('config.factory')->get('auth0.settings');
  return [
    'auth0.widget' => [
      'js' => [
        $config->get('auth0_widget_cdn') => [
          'type' => 'external',
        ],
      ],
    ],
  ];
}
