auth0.settings:
  type: config_object
  label: 'Auth0 settings'
  mapping:
    auth0_username_claim:
      type: string
      label: 'Username claim'
    auth0_role_mapping:
      type: string
      label: 'Role mapping'
    auth0_claim_mapping:
      type: string
      label: 'Claim mapping'
    auth0_sync_role_mapping:
      type: boolean
      label: 'Sync role mapping'
    auth0_sync_claim_mapping:
      type: boolean
      label: 'Sync claim mapping'
    auth0_requires_verified_email:
      type: boolean
      label: 'Requires verified email'
    auth0_client_id:
      type: string
      label: 'Client ID'
    auth0_client_secret:
      type: string
      label: 'Client secret'
    auth0_client_secret_key:
      type: string
      label: 'Client secret key'
    auth0_domain:
      type: string
      label: 'Auth0 domain'
    auth0_cookie_secret:
      type: string
      label: 'Cookie secret'
    auth0_cookie_secret_key:
      type: string
      label: 'Cookie secret key'
